### ISSUE TITLE
[META] Tests to skip on cloud

### ISSUE THREAD

**Issue by chrisronline** [elastic/stack-monitoring#31]
This is a meta ticket to contain all the various tests we need to skip for cloud and the reason why.

## Api integration
- [ ] https://github.com/elastic/kibana/issues/30707
- [ ] https://github.com/elastic/kibana/issues/30708
- [ ] https://github.com/elastic/kibana/issues/30709

## Functional
...

**Comment by chrisronline** [comment]
cc @liza-mae

**Comment by chrisronline** [comment]
We need to follow up with each of these with a resolution in the near future.
